"""empty message

Revision ID: 2d14ef761ad2
Revises: 
Create Date: 2017-05-15 18:31:11.482548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d14ef761ad2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_model_name'), 'data_model', ['name'], unique=False)
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('classno', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['data_model.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('classno', 'model_id')
    )
    op.create_table('label',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('data_class_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['data_class_id'], ['data_class.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'position')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('label')
    op.drop_table('data_class')
    op.drop_table('document')
    op.drop_index(op.f('ix_data_model_name'), table_name='data_model')
    op.drop_table('data_model')
    # ### end Alembic commands ###
